services:
  fossflow:
    image: stnsmith/fossflow:latest
    pull_policy: always
    ports:
      - 8180:80
    environment:
      - NODE_ENV=production
      - ENABLE_SERVER_STORAGE=${ENABLE_SERVER_STORAGE:-true}
      - ENABLE_GIT_BACKUP=${ENABLE_GIT_BACKUP:-false}
